### ISSUE TITLE
System for Integrating other Static Type Checkers

### ISSUE THREAD

**Issue by shadowtime2000** [alephjs/alef-component#11]
I am a big fan of Typescript too, but I feel like requiring Typescript wouldn't be that good, especially if people prefer other type checkers such as Flow. It seems like TS isn't actually being used intensively with this, it is just used for detecting what the purpose of a variable is. People could write stuff using the precompilation API to convert their code to TS, but that seems a little unnecessary. What if we allowed users to write plugins with the precompilation API that can give the types of the different variables?

```js
[
	{
		name: "basicConst",
		type: "Const", // maybe switch out for an enum provided to plugin?
		value: "'some string'"
	},
	{
		name: "memoizedValue",
		type: "Memo",
		value: "number * 2"
	}
]
```

**Comment by shadowtime2000** [comment]
Of course TS will still be built in. Kind of basing the format off of [#9 (issue comment)](https://github.com/alephjs/alef-component/issues/9#issuecomment-743966500).

**Comment by ije** [comment]
i understand, but i want to keep it simple, better no flow, no babel etc, although we will provide the `precompile` for plugin authors, but for end users i always wish zero configuration, write components without importing unnecessary modules as possible, so i perfer using types declaration and labeled statement to specify some mvvm features. and on other hand i wish it has some strong and unique concepts (like types statement) that can help to build identity, although it may be not kind for beginning users, but i think people should use typescript instead of javascript or them should not use alef component.

**Comment by shadowtime2000** [comment]
That makes sense, Alef will be for people who know a bit more about JS and TS.

**Comment by ije** [comment]
as a FE engineer, no matter react, vuejs, angular, or svelte you have to learn many mvvm concepts beyond vanilla JS and DOM, so i think it is ok for most people. and we should focus on the core concept, let community help to perfect the eco-system.
